### ISSUE TITLE
Als zorgcoördinator wil ik dat patiënten de Activity Tracker niet kunnen misleiden om een activiteit te voltooien.

### ISSUE THREAD

**Issue by arteeh** [winactivitytracker/activitytracker#22]
### Beschrijving

Een gebruiker mag het systeem niet bewust of onbewust foppen. Het aantal gestelde stappen en overige sportinformatie moet accuraat zijn.

### Acceptatiecriteria

- [ ] Na een sessie van vijf minuten waar een gebruiker niet sport maar wel bewegingen maakt, wordt geen enkele keer aangegeven dat er wel is gesport. 
- [ ] Het aantal getelde stappen mag vergeleken met het werkelijke aantal gezette stappen afwijken met maximaal 5 procent.

### Definition of Done

*Als een zin niet van toepassing is kun je hem gewoon aanvinken.*

- [ ] Alle functionele documentatie betreffende het item is geschreven
- [ ] Alle technische documentatie betreffende het item is geschreven
- [ ] Na aanvraag van een review, wordt dit gedaan door een ander teamlid
- [ ] Unit tests en andere relevante tests zijn geschreven voor de gemaakte functionaliteit
- [ ] Alle gemaakte tests slagen
- [ ] De gemaakte functionaliteit voldoet aan de beschrijving bij het item op GitLab
- [ ] De geschreven code voldoet aan de code-conventies besproken in de samenwerkingsafspraken
- [ ] De gemaakte code moet gecommit zijn naar de Git repository
