### ISSUE TITLE
Als drager van de Activity Tracker wil ik dat de apparaten minstens een dag aan batterijduur hebben, zodat ik deze gedurende de dag kan blijven gebruiken.

### ISSUE THREAD

**Issue by arteeh** [winactivitytracker/activitytracker#24]
### Beschrijving

Alle apparaten moeten een dag blijven werken. Dit doen we door onze hardware zo aan te sturen en in te stellen waardoor zo weinig mogelijk stroom wordt gebruikt.

Joost heeft aangegeven dat dit een must-have is.

### Acceptatiecriteria

- [ ] Het verzamelpunt kan 12 uur lang informatie blijven verzamelen en verwerken zonder opgeladen te hoeven worden.
- [ ] Beide meetpunten kunnen 12 uur lang data verzamelen en opsturen zonder opgeladen te hoeven worden.

### Definition of Done

*Als een zin niet van toepassing is kun je hem gewoon aanvinken.*

- [ ] Alle functionele documentatie betreffende het item is geschreven
- [ ] Alle technische documentatie betreffende het item is geschreven
- [ ] Na aanvraag van een review, wordt dit gedaan door een ander teamlid
- [ ] Unit tests en andere relevante tests zijn geschreven voor de gemaakte functionaliteit
- [ ] Alle gemaakte tests slagen
- [ ] De gemaakte functionaliteit voldoet aan de beschrijving bij het item op GitLab
- [ ] De geschreven code voldoet aan de code-conventies besproken in de samenwerkingsafspraken
- [ ] De gemaakte code moet gecommit zijn naar de Git repository
