### ISSUE TITLE
Als drager van de Activity Tracker wil ik dat de apparaten een week aan batterijduur hebben, zodat ik de apparaten weinig hoef op te laden.

### ISSUE THREAD

**Issue by arteeh** [winactivitytracker/activitytracker#25]
### Beschrijving

Dezelfde story als degene met een dag, alleen langer. Joost heeft aangegeven dat dit een 'nice to have' is.

### Acceptatiecriteria

- [ ] Het verzamelpunt kan 7 dagen lang informatie blijven verzamelen en verwerken zonder opgeladen te hoeven worden.
- [ ] Beide meetpunten kunnen 7 dagen lang data verzamelen en opsturen zonder opgeladen te hoeven worden.

### Definition of Done

*Als een zin niet van toepassing is kun je hem gewoon aanvinken.*

- [ ] Alle functionele documentatie betreffende het item is geschreven
- [ ] Alle technische documentatie betreffende het item is geschreven
- [ ] Na aanvraag van een review, wordt dit gedaan door een ander teamlid
- [ ] Unit tests en andere relevante tests zijn geschreven voor de gemaakte functionaliteit
- [ ] Alle gemaakte tests slagen
- [ ] De gemaakte functionaliteit voldoet aan de beschrijving bij het item op GitLab
- [ ] De geschreven code voldoet aan de code-conventies besproken in de samenwerkingsafspraken
- [ ] De gemaakte code moet gecommit zijn naar de Git repository
