### ISSUE TITLE
Als drager van de Activity Tracker wil ik tijdens mijn workout zien hoe lang en hoe hard ik een activiteit heb gedaan, zodat ik live mijn prestaties kan bijhouden.

### ISSUE THREAD

**Issue by arteeh** [winactivitytracker/activitytracker#26]
### Beschrijving

We laten deze informatie op een OLED schermpje op het verzamelpunt zien.

Joost heeft aangegeven dat dit een “nice to have” is.

### Acceptatiecriteria

- [ ] De gebruiker kan zien welke activiteit de software denkt dat hij doet.
- [ ] De gebruiker kan zien hoe lang hij deze activiteit al blijkt te doen.
- [ ] De gebruiker kan zien hoe snel hij gaat (als dit relevant is voor de sport).

### Definition of Done

*Als een zin niet van toepassing is kun je hem gewoon aanvinken.*

- [ ] Alle functionele documentatie betreffende het item is geschreven
- [ ] Alle technische documentatie betreffende het item is geschreven
- [ ] Na aanvraag van een review, wordt dit gedaan door een ander teamlid
- [ ] Unit tests en andere relevante tests zijn geschreven voor de gemaakte functionaliteit
- [ ] Alle gemaakte tests slagen
- [ ] De gemaakte functionaliteit voldoet aan de beschrijving bij het item op GitLab
- [ ] De geschreven code voldoet aan de code-conventies besproken in de samenwerkingsafspraken
- [ ] De gemaakte code moet gecommit zijn naar de Git repository
