### ISSUE TITLE
Als drager van de Activity Tracker wil ik mijn gezette stappen kunnen zien, zodat ik weet hoeveel ik die dag heb bewogen.

### ISSUE THREAD

**Issue by arteeh** [winactivitytracker/activitytracker#28]
### Beschrijving

We laten deze informatie op een OLED schermpje op het verzamelpunt zien.

Joost heeft aangegeven dat dit een “nice to have” is.

### Acceptatiecriteria

- [ ] De gebruiker kan het systeem gebruiken om het actuele aantal getelde stappen te lezen.

### Definition of Done

*Als een zin niet van toepassing is kun je hem gewoon aanvinken.*

- [ ] Alle functionele documentatie betreffende het item is geschreven
- [ ] Alle technische documentatie betreffende het item is geschreven
- [ ] Na aanvraag van een review, wordt dit gedaan door een ander teamlid
- [ ] Unit tests en andere relevante tests zijn geschreven voor de gemaakte functionaliteit
- [ ] Alle gemaakte tests slagen
- [ ] De gemaakte functionaliteit voldoet aan de beschrijving bij het item op GitLab
- [ ] De geschreven code voldoet aan de code-conventies besproken in de samenwerkingsafspraken
- [ ] De gemaakte code moet gecommit zijn naar de Git repository
